name: CI

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: |
            build/gradle-jvm
            ~/.nuget/packages
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-Build-${{ hashFiles('gradlew.bat', 'src/dotnet/*/*.csproj', 'src/dotnet/*.props', 'gradle-wrapper.properties') }}
      - run: ./gradlew :rdgen --no-daemon
      - run: ./gradlew :buildPlugin --no-daemon
      - uses: mad9000/actions-find-and-replace-string@5
        id: fix_branch_name
        with:
          source: ${{ github.ref_name }}
          find: '/'
          replace: '-'
      - uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/head/release/')
        with:
          name: ${{ github.event.repository.name }}.CI.${{ steps.fix_branch_name.outputs.value }}
          path: output
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: |
            build/gradle-jvm
            packages
            ~/.nuget/packages
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-Test-${{ hashFiles('gradlew.bat', 'src/dotnet/*/*.csproj', 'src/dotnet/*.props', 'gradle-wrapper.properties') }}
      - run: ./gradlew :rdgen --no-daemon
      - run: ./gradlew :testDotNet --no-daemon
