name: CI

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: |
            build/gradle-jvm
            ~/.nuget/packages
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-Build-${{ hashFiles('gradlew.bat', 'src/dotnet/*/*.csproj', 'src/dotnet/*.props', 'gradle-wrapper.properties') }}
      - run: ./gradlew :rdgen --no-daemon
      - run: ./gradlew :buildPlugin --no-daemon
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ github.event.repository.name }}.CI.${{ github.ref_name//\//- }}
          path: output
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: |
            build/gradle-jvm
            packages
            ~/.nuget/packages
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-Test-${{ hashFiles('gradlew.bat', 'src/dotnet/*/*.csproj', 'src/dotnet/*.props', 'gradle-wrapper.properties') }}
      - run: ./gradlew :rdgen --no-daemon
      - run: ./gradlew :testDotNet --no-daemon
